# -*- coding: utf-8 -*-
"""party.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qNShbNfAGm95OvK1AtYGKaPwbx7fFe9b
"""

import streamlit as st
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

# =========================
# 1. Crear DataFrame
# =========================

data = {
    "mm": [0.7,13.2,0.1,9,33.5,105,145.6,235.1,159.6,45.5,14.6,3,
           12.3,11.7,8.4,2.5,64.6,211.6,131.4,173.7,196.7,71,1.6,8.7],

    "tp": [16.4,17.4,20.3,21,23.6,27.5,19.2,19.4,19.3,16.9,17.4,15.5,
           15.9,17.5,19.8,20.2,21.6,19.2,18.7,19,19.3,17.9,16.3,15.5],

    "te": [2,2,1,0,0,0,2,2,1,0,1,0,
           2,2,1,0,0,0,2,2,1,0,1,0],

    "party": [10240,11197,7014,11620,15239,9549,6619,12156,3796,
              4435.5,4409,2731,7738.7,7167,1441.65,8285.48,4097,
              9721.5,6579.42,8502,3796,2494,279,3322.43]
}

df = pd.DataFrame(data)

# =========================
# 2. Variables
# =========================

X = df[["mm", "tp", "te"]]
y = df["party"]

# =========================
# 3. Modelo Random Forest
# =========================

model = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

model.fit(X, y)

# =========================
# 4. Interfaz Streamlit
# =========================

st.title("Pronóstico de Party con Random Forest")

st.write("Ingrese los valores de las características:")

mm_input = st.number_input("mm", min_value=0.0, value=10.0)
tp_input = st.number_input("tp", min_value=0.0, value=18.0)
te_input = st.selectbox("te", [0, 1, 2])

# =========================
# 5. Predicción
# =========================

if st.button("Pronosticar"):

    input_data = pd.DataFrame({
        "mm": [mm_input],
        "tp": [tp_input],
        "te": [te_input]
    })

    prediction = model.predict(input_data)[0]

    st.success(f"Pronóstico de party: {prediction:.2f}")


# --- Personalización de diseño ---
st.markdown("""
<style>
    .stApp {
        background-color: #00BFFF;
    }
    .css-1d391kg {
        color: #00BFFF;
    }
</style>
""", unsafe_allow_html=True)
